== mTLS-your-silvercrest
This project extends the solution to free the Silvercrest (Lidl/Tuya) Smart Home Gateway 
from the cloud by securing the ethernet connection by mTLS. This avoids expose of
your gateway to any users/guests in your network - and secures the gateway solution professionally.

Upstreams:
* https://paulbanks.org/projects/lidl-zigbee/
* https://github.com/Ordspilleren/lidl-gateway-freedom
* https://community.openhab.org/t/hacking-the-lidl-silvercrest-zigbee-gateway-a-step-by-step-tutorial/129660

== Generate a pair of self-signed certificates
-----
-----

== Use socat to connect to gateway as regular device

You can check whether your `socat` supports SSL by:
-----
socat -V |grep SSL
-----

On the gateway client, you can use `socat` to establish the mTLS secured connection.
It is acting as client, so the connection requires client key and certificate for authentication.
`socat` demands a combined pem file for the client, that could be generated like: 
-----
cat client.key client.crt >client.pem
-----

Then, the connection is established with:
-----
socat -dd pty,link=/dev/ttyZigate1,raw,user-late=zwgate,group-late=dialout \
      openssl-connect:zigate.my.domain:4888,cert=path_to/client.pem,cafile=path_to/gwserver.pem
-----
It is recommended to run `socat` as service with automatic restart or as restarting container.

-----
cat tlsserialgateway | ssh -p2333 root@<gateway IP address> "cat >/tuya/tlsserialgateway"

# copy server key + cert
cat gwserver.crt | ssh -o HostKeyAlgorithms=+ssh-rsa root@<gateway IP address> "cat >/etc/tls/gwserver.crt"
cat gwserver.key | ssh -o HostKeyAlgorithms=+ssh-rsa root@<gateway IP address> "cat >/etc/tls/gwserver.key"
cat client.crt | ssh -o HostKeyAlgorithms=+ssh-rsa root@<gateway IP address> "cat >/etc/tls/trust.crt"
-----

-----
mkdir ~/.ssh
dropbearkey -t ed25519 -f ~/.ssh/id_dropbear
-----